version: '2'
services:
  jira-data:
    image: busybox
    labels:
      io.rancher.container.start_once: true
    {{- if ne .Values.host_label ""}}
      io.rancher.scheduler.affinity:host_label: ${host_label}
    {{- end}}
    volumes:
      - jiraData:/var/atlassian/jira
  jira:
    image: cptactionhank/atlassian-jira-software:7.4.0
    tty: true
    stdin_open: true
    labels:
      io.rancher.sidekicks: jira-data
    {{- if ne .Values.host_label ""}}
      io.rancher.scheduler.affinity:host_label: ${host_label}
    {{- end}}
    environment:
      - CATALINIA_OPTS=-Xms${min} -Xmx${max} -Datlassian.plugins.enable.wait=${plugin_timeout} ${jvm_args}
      - X_PROXY_PORT=${proxy_port}
      - X_PROXY_NAME=${proxy_name}
      - X_PROXY_SCHEME=${proxy_scheme}
      - X_PATH=${context_path}
    external_links:
      - ${database_link}:database
    volumes:
      - jiraData:/var/atlassian/jira
    volumes_from:
      - jira-data
volumes:
  jiraData:
    driver: ${VOLUME_DRIVER}
    per_container: true