jira:
  image: cptactionhank/atlassian-jira-software:7.4.0
  environment:
    - CATALINIA_OPTS=-Xms${heap_size} -Xmx${heap_size} -Datlassian.plugins.enable.wait=${plugin_timeout} ${jvm_args}
    - X_PROXY_PORT=${proxy_port}
    - X_PROXY_NAME=${proxy_name}
    - X_PROXY_SCHEME=${proxy_scheme}
    - X_PATH=${context_path}
  external_links:
    - ${database_link}:database
  volumes:
    - ${jira_home}:/var/atlassian/jira