.catalog:
  name: "Jira Software"
  version: "7.4.0"
  description: "Plan, track, and manage your agile and software development projects in Jira. Customize your workflow, collaborate, and release great software."
  questions:
    - variable: "context_path"
      label: "Context path"
      description: |
        The context path under which Bitbucket will be available
      type: "string"
      default: "/"
      required: true
    - variable: "proxy_name"
      label: "Proxy name"
      description: |
        When behind a proxy, specify the name through which clients will connect to Bitbucket. For example: bitbucket.mycompany.com
      type: "string"
      required: false
    - variable: "proxy_port"
      label: "Proxy port"
      description: |
        When behind a proxy, specify the port through which clients will connect to Bitbucket
      type: "int"
      required: false
    - variable: "proxy_scheme"
      label: "Proxy scheme"
      description: |
        When behind a proxy, specify the protocol clients will use to connect to Bitbucket
      type: "enum"
      options:
        - http
        - https
      default: http
      required: false
    - variable: "min"
      label: "Minimum JVM Memory Size"
      description: |
        The size of the heap the JVM can allocate
      type: "string"
      default: "2g"
      required: true
    - variable: "max"
      label: "Maximum JVM Memory Size"
      description: |
        The size of the heap the JVM can allocate
      type: "string"
      default: "3g"
      required: true
    - variable: "database_link"
      label: "Database"
      description: |
        Service link to the database. This will be mapped to the container as 'database'
      type: "service"
      required: true
    - variable: "VOLUME_DRIVER"
      description: "The VOLUME driver to associate with this server"
      label: "VOLUME Driver"
      required: true
      default: "local"
      type: enum
      options: # List of options if using type of `enum`
        - local
        - rancher-nfs
        - rancher-efs
        - rancher-ebs
    - variable: host_label
      label: "Host with Label to put postgres on"
      description: |
        Host label to use as postgres 'value' tag.
        Example: 'app_server=true'
      required: false
      default: ""
      type: "string"
    - variable: "plugin_timeout"
      label: "Jira Plugin Timeout"
      required: true
      default: "300"
      type: "string"
jira:
  scale: 1
  health_check:
    port: 8080
    interval: 2000
    initializing_timeout: 60000
    unhealthy_threshold: 3
    strategy: recreate
    healthy_threshold: 2
    response_timeout: 2000