version: '2'
services:
  bitbucket-data:
    image: busybox
    labels:
      io.rancher.container.start_once: true
    {{- if ne .Values.host_label ""}}
      io.rancher.scheduler.affinity:host_label: ${host_label}
    {{- end}}
    volumes:
      - btdata:/var/atlassian/bitbucket
  bitbucket:
    image: blacklabelops/bitbucket:5.5.0
    tty: true
    stdin_open: true
    labels:
      io.rancher.sidekicks: bitbucket-data
    {{- if ne .Values.host_label ""}}
      io.rancher.scheduler.affinity:host_label: ${host_label}
    {{- end}}
    environment:
      - BITBUCKET_PROXY_NAME=${proxy_name}
      - BITBUCKET_PROXY_PORT=${proxy_port}
      - BITBUCKET_PROXY_SCHEME=${proxy_scheme}
      - BITBUCKET_CONTEXT_PATH=${context_path}
      - JVM_MINIMUM_MEMORY=${min}
      - JVM_MAXIMUM_MEMORY=${max}
    external_links:
      - ${database_link}:database
    volumes:
      - btdata:/var/atlassian/bitbucket
    volumes_from:
      - bitbucket-data
volumes:
  btdata:
    driver: ${VOLUME_DRIVER}
    per_container: true
