name: Jira Software
description: |
  Plan, track, and manage your agile and software development projects in Jira. Customize your workflow, collaborate, and release great software.
version: 7.4.0
category: Collaboration