version: '2'
services:
  bamboo-data:
    image: busybox
    labels:
      io.rancher.container.start_once: true
    {{- if ne .Values.host_label ""}}
      io.rancher.scheduler.affinity:host_label: ${host_label}
    {{- end}}
    volumes:
      - bambooData:/var/atlassian/bamboo
  bamboo:
    image: cptactionhank/atlassian-bamboo:6.2.2
    tty: true
    stdin_open: true
    labels:
      io.rancher.sidekicks: bamboo-data
    {{- if ne .Values.host_label ""}}
      io.rancher.scheduler.affinity:host_label: ${host_label}
    {{- end}}
    environment:
      - CATALINIA_OPTS=-Xms${min} -Xmx${max} -Datlassian.plugins.enable.wait=${plugin_timeout} ${jvm_args}
      - X_PROXY_PORT=${proxy_port}
      - X_PROXY_NAME=${proxy_name}
      - X_PROXY_SCHEME=${proxy_scheme}
      - X_PATH=${context_path}
    external_links:
      - ${database_link}:database
    volumes:
      - bambooData:/var/atlassian/bamboos
    volumes_from:
      - bamboo-data
volumes:
  bambooData:
    driver: ${VOLUME_DRIVER}
    per_container: true