confluence:
  image: cptactionhank/atlassian-confluence:6.3.4
  environment:
    - CATALINIA_OPTS=-Xms${min} -Xmx${max} -Datlassian.plugins.enable.wait=${plugin_timeout} ${jvm_args}
    - X_PROXY_PORT=${proxy_port}
    - X_PROXY_NAME=${proxy_name}
    - X_PROXY_SCHEME=${proxy_scheme}
    - X_PATH=${context_path}
  external_links:
    - ${database_link}:database
  volumes:
    - ${home}:/var/atlassian/confluence