version: '2'
services:
  confluence-data:
    image: busybox
    labels:
      io.rancher.container.start_once: true
    {{- if ne .Values.host_label ""}}
      io.rancher.scheduler.affinity:host_label: ${host_label}
    {{- end}}
    volumes:
      - confluenceData:/var/atlassian/confluence
  confluence:
    image: cptactionhank/atlassian-confluence:6.3.4
    tty: true
    stdin_open: true
    labels:
      io.rancher.sidekicks: confluence-data
    {{- if ne .Values.host_label ""}}
      io.rancher.scheduler.affinity:host_label: ${host_label}
    {{- end}}
    environment:
      - CATALINIA_OPTS=-Xms${min} -Xmx${max} -Datlassian.plugins.enable.wait=${plugin_timeout} ${jvm_args}
      - X_PROXY_PORT=${proxy_port}
      - X_PROXY_NAME=${proxy_name}
      - X_PROXY_SCHEME=${proxy_scheme}
      - X_PATH=${context_path}
    external_links:
      - ${database_link}:database
    volumes:
      - confluenceData:/var/atlassian/confluence
    volumes_from:
      - confluence-data
volumes:
  confluenceData:
    driver: ${VOLUME_DRIVER}
    per_container: true