bind:
  image: digitallumberjack/docker-bind9:latest
  labels:
    io.rancher.scheduler.affinity:host_label: ${BIND_HOST_LABEL}
  ports:
     - ${BIND_PORT}:53/tcp
     - ${BIND_PORT}:53/udp
  environment:
   - BIND9_IP=${BIND_IP}
   - BIND9_ROOTDOMAIN=${BIND_ROOT_DOMAIN}
   - BIND9_KEYNAME=${BIND_KEYNAME}
   - BIND9_KEY_ALGORITHM=${BIND_ALGORITHM}
   - BIND9_KEY=${BIND_KEY}
   - BIND9_FORWARDERS=${BIND_FORWARDERS}
   - BIND9_IPV4ONLY=${BIND_IPV4_ONLY}
   - BIND9_QUERY_CACHE_ACCEPT=${BIND_QUERY_CACHE_IP};
   - BIND9_RECURSION_ACCEPT=${BIND_RECURSION_IP};
   - BIND9_STATIC_ENTRIES=${BIND_STATIC_ENTRIES}
