name: Bitbucket (One43)
description: |
  Collaborate on code with inline comments and pull requests. Manage and share your Git repositories to build and ship software, as a team.
version: 4.10.1
category: Versioning